[workspace]
resolver = "3"
members = ["backend", "interface", "**/macros"]

[workspace.dependencies]
wedding_interface.path = "interface"
chrono = "0.4.30"
serde = { version = "1.0.228", features = ["derive"] }