// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateGuestInfoRequest = { side: Side, name: string, relationship: string, estimated_count: number, };

export type GetGuestListResponse = { guest_list: Array<GuestInfoView>, };

export type GuestInfoView = { id: string, side: Side, name: string, relationship: string, estimated_count: number, confirmed_count: number, created_by: string, created_at: string, updated_by: string, updated_at: string, };

export type LoginRequest = { name: string, password: string, };

export type LoginResponse = { name: string, login_time: string, };

export type RemoveGuestPathParams = { id: string, };

export type Side = "Bride" | "Groom";
