// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { name: string, password: string, };

export type LoginResponse = { name: string, login_time: string, };
