// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateGuestInfoRequest = { side: Side, name: string, relationship: string, estimatedCount: number, };

export type GetGuestListResponse = { guestList: Array<GuestInfoView>, };

export type GuestInfoView = { id: string, side: Side, name: string, relationship: string, estimatedCount: number, confirmedCount: number | null, createdBy: string, createdAt: string, updatedBy: string, updatedAt: string, };

export type IdPathParams = { id: string, };

export type InvitationInfoResponse = { name: string, status: InvitationStatus, count: number, };

export type InvitationStatus = "pENDING" | "cONFIRMED";

export type LoginRequest = { name: string, password: string, };

export type LoginResponse = { name: string, loginTime: string, };

export type Side = "BRIDE" | "GROOM";

export type UpdateGuestCountRequest = { count: number, };

export type UpdateGuestInfoRequest = { side: Side, name: string, relationship: string, estimatedCount: number, confirmedCount: number | null, };
