[package]
name = "wedding_interface"
version = "0.1.0"
authors = ["ianlau <ianlauyin@gmail.com>"]
edition = "2024"

[lib]
path = "src/types.rs"

[dependencies]
ts-rs = { version = "11.0.1", features = ["chrono-impl"]}
chrono = { workspace = true, features = ["serde"]}
serde.workspace =true